### ISSUE TITLE
Hassan

### ISSUE THREAD

**Issue by Hassan8377** [vappiah/Transcriptomics#1]
Hi,
Thank you for the nice tutorial.
The issue i cant download the data. The error message as follows:

(rna-seq) au_hishaq@ADAFSA-VM-01:~/rna-seq$ wget ftp://ftp.ccb.jhu.edu/pub/RNAseq_protocol/chrX_data.tar.gz
--2022-04-19 00:13:36--  ftp://ftp.ccb.jhu.edu/pub/RNAseq_protocol/chrX_data.tar.gz
           => ‘chrX_data.tar.gz.7’
Resolving ftp.ccb.jhu.edu (ftp.ccb.jhu.edu)... 128.220.174.63
Connecting to ftp.ccb.jhu.edu (ftp.ccb.jhu.edu)|128.220.174.63|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/RNAseq_protocol ... done.
==> SIZE chrX_data.tar.gz ... 2113551170
==> PASV ... done.    ==> RETR chrX_data.tar.gz ... done.
Length: 2113551170 (2.0G) (unauthoritative)

chrX_data.tar.gz.7                        0%[                                                                               ]       0  --.-KB/s    in 0s

2022-04-19 00:13:39 (0.00 B/s) - Data connection: Connection reset by peer; Data transfer aborted.
Retrying.

--2022-04-19 00:13:41--  ftp://ftp.ccb.jhu.edu/pub/RNAseq_protocol/chrX_data.tar.gz
  (try: 2) => ‘chrX_data.tar.gz.7’
==> CWD not required.
==> SIZE chrX_data.tar.gz ... 2113551170
==> PASV ... done.    ==> RETR chrX_data.tar.gz ... done.
Length: 2113551170 (2.0G) (unauthoritative)

chrX_data.tar.gz.7                        0%[                                                                               ]       0  --.-KB/s    in 0s

2022-04-19 00:13:42 (0.00 B/s) - Data connection: Connection reset by peer; Data transfer aborted.
Retrying.

--2022-04-19 00:13:44--  ftp://ftp.ccb.jhu.edu/pub/RNAseq_protocol/chrX_data.tar.gz
  (try: 3) => ‘chrX_data.tar.gz.7’
==> CWD not required.
==> SIZE chrX_data.tar.gz ... 2113551170
==> PASV ... done.    ==> RETR chrX_data.tar.gz ... done.
Length: 2113551170 (2.0G) (unauthoritative)

chrX_data.tar.gz.7                        0%[                                                                               ]       0  --.-KB/s    in 0s

2022-04-19 00:13:45 (0.00 B/s) - Data connection: Connection reset by peer; Data transfer aborted.
Retrying.

**Comment by vappiah** [comment]
Try using a different network.

**Comment by HassanIshag** [comment]
Dear,
Thank you for your response. I tried a different network in different days but unfortunately same error and got 0kb downloaded. Returned error: Data connection: Connection reset by peer; Data transfer aborted.
Can you help me upload the data in google drive or any ways so us to get it and go through the analysis?

**Comment by vappiah** [comment]
Try this command
wget --no-check-certificate  dowloadlink

**Comment by HassanIshag** [comment]
Hello
Thank you for suggesting the solution. However, still not working as shwon below:
(rna-seq) au_hishaq@ADAFSA-VM-01:~/rna-seq$ wget --no-check-certificate ftp://ftp.ccb.jhu.edu/pub/RNAseq_protocol/chrX_data.tar.gz
--2022-04-22 23:56:22--  ftp://ftp.ccb.jhu.edu/pub/RNAseq_protocol/chrX_data.tar.gz
           => ‘chrX_data.tar.gz.4’
Resolving ftp.ccb.jhu.edu (ftp.ccb.jhu.edu)... 128.220.174.63
Connecting to ftp.ccb.jhu.edu (ftp.ccb.jhu.edu)|128.220.174.63|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/RNAseq_protocol ... done.
==> SIZE chrX_data.tar.gz ... 2113551170
==> PASV ... done.    ==> RETR chrX_data.tar.gz ... done.
Length: 2113551170 (2.0G) (unauthoritative)

chrX_data.tar.gz.4             0%[                                              ]       0  --.-KB/s    in 0s

2022-04-22 23:56:24 (0.00 B/s) - Data connection: Connection reset by peer; Data transfer aborted.
Retrying.

**Comment by vappiah** [comment]
Hi @Hassan8377, the command works perfectly. I suggest  you try on a different Computer.

**Comment by HassanIshag** [comment]
Thank you dear, BTW, i tried three different computers and all returned same error. I will try to do troubleshooting and see how it goes.

**Comment by vappiah** [comment]
@HassanIshag Note that everything should be done in a Linux environment.

For now, I am closing this issue.
